

// This is a simplified dataset of Indian locations
// In a production app, you would use a more comprehensive API or dataset

export const indianStates = [
    "Andhra Pradesh",
    "Arunachal Pradesh",
    "Assam",
    "Bihar",
    "Chhattisgarh",
    "Goa",
    "Gujarat",
    "Haryana",
    "Himachal Pradesh",
    "Jharkhand",
    "Karnataka",
    "Kerala",
    "Madhya Pradesh",
    "Maharashtra",
    "Manipur",
    "Meghalaya",
    "Mizoram",
    "Nagaland",
    "Odisha",
    "Punjab",
    "Rajasthan",
    "Sikkim",
    "Tamil Nadu",
    "Telangana",
    "Tripura",
    "Uttar Pradesh",
    "Uttarakhand",
    "West Bengal",
    "Andaman and Nicobar Islands",
    "Chandigarh",
    "Dadra and Nagar Haveli and Daman and Diu",
    "Delhi",
    "Jammu and Kashmir",
    "Ladakh",
    "Lakshadweep",
    "Puducherry",
  ];
  
 

  export const stateDistricts: { state: string; districts: string[] }[] =
          [
            { state: "Andhra Pradesh", districts: ["Anantapur", "Chittoor", "East Godavari", "Guntur", "Kadapa", "Krishna", "Kurnool", "Nellore", "Prakasam", "Srikakulam", "Visakhapatnam", "Vizianagaram", "West Godavari"] },
            { state: "Arunachal Pradesh", districts: ["Anjaw", "Changlang", "Dibang Valley", "East Kameng", "East Siang", "Kamle", "Kra Daadi", "Kurung Kumey", "Lepa Rada", "Lohit", "Longding", "Lower Dibang Valley", "Lower Siang", "Lower Subansiri", "Namsai", "Pakke Kessang", "Papum Pare", "Shi Yomi", "Siang", "Tawang", "Tirap", "Upper Siang", "Upper Subansiri", "West Kameng", "West Siang"] },
            { state: "Assam", districts: ["Baksa", "Barpeta", "Biswanath", "Bongaigaon", "Cachar", "Charaideo", "Chirang", "Darrang", "Dhemaji", "Dhubri", "Dibrugarh", "Goalpara", "Golaghat", "Hailakandi", "Hojai", "Jorhat", "Kamrup", "Kamrup Metropolitan", "Karbi Anglong", "Karimganj", "Kokrajhar", "Lakhimpur", "Majuli", "Morigaon", "Nagaon", "Nalbari", "Dima Hasao", "Sivasagar", "Sonitpur", "South Salmara-Mankachar", "Tinsukia", "Udalguri", "West Karbi Anglong"] },
            { state: "Bihar", districts: ["Araria", "Arwal", "Aurangabad", "Banka", "Begusarai", "Bhagalpur", "Bhojpur", "Buxar", "Darbhanga", "East Champaran", "Gaya", "Gopalganj", "Jamui", "Jehanabad", "Kaimur", "Katihar", "Khagaria", "Kishanganj", "Lakhisarai", "Madhepura", "Madhubani", "Munger", "Muzaffarpur", "Nalanda", "Nawada", "Patna", "Purnia", "Rohtas", "Saharsa", "Samastipur", "Saran", "Sheikhpura", "Sheohar", "Sitamarhi", "Siwan", "Supaul", "Vaishali", "West Champaran"] },
            { state: "Chhattisgarh", districts: ["Balod", "Baloda Bazar", "Balrampur", "Bastar", "Bemetara", "Bijapur", "Bilaspur", "Dantewada", "Dhamtari", "Durg", "Gariaband", "Gaurela-Pendra-Marwahi", "Janjgir-Champa", "Jashpur", "Kabirdham", "Kanker", "Kondagaon", "Korba", "Korea", "Mahasamund", "Mungeli", "Narayanpur", "Raigarh", "Raipur", "Rajnandgaon", "Sukma", "Surajpur", "Surguja"] },
            { state: "Goa", districts: ["North Goa", "South Goa"] },
            { state: "Gujarat", districts: ["Ahmedabad", "Amreli", "Anand", "Aravalli", "Banaskantha", "Bharuch", "Bhavnagar", "Botad", "Chhota Udaipur", "Dahod", "Dang", "Devbhoomi Dwarka", "Gandhinagar", "Gir Somnath", "Jamnagar", "Junagadh", "Kheda", "Kutch", "Mahisagar", "Mehsana", "Morbi", "Narmada", "Navsari", "Panchmahal", "Patan", "Porbandar", "Rajkot", "Sabarkantha", "Surat", "Surendranagar", "Tapi", "Vadodara", "Valsad"] },
            { state: "Haryana", districts: ["Ambala", "Bhiwani", "Charkhi Dadri", "Faridabad", "Fatehabad", "Gurugram", "Hisar", "Jhajjar", "Jind", "Kaithal", "Karnal", "Kurukshetra", "Mahendragarh", "Nuh", "Palwal", "Panchkula", "Panipat", "Rewari", "Rohtak", "Sirsa", "Sonipat", "Yamunanagar"] },
            { state: "Himachal Pradesh", districts: ["Bilaspur", "Chamba", "Hamirpur", "Kangra", "Kinnaur", "Kullu", "Lahaul and Spiti", "Mandi", "Shimla", "Sirmaur", "Solan", "Una"] },
            { state: "Jharkhand", districts: ["Bokaro", "Chatra", "Deoghar", "Dhanbad", "Dumka", "East Singhbhum", "Garhwa", "Giridih", "Godda", "Gumla", "Hazaribagh", "Jamtara", "Khunti", "Koderma", "Latehar", "Lohardaga", "Pakur", "Palamu", "Ramgarh", "Ranchi", "Sahibganj", "Seraikela Kharsawan", "Simdega", "West Singhbhum"] }
           , { state: "Karnataka", districts: [
                  "Bagalkot",
                  "Bangalore Rural",
                  "Bangalore Urban",
                  "Belagavi",
                  "Ballari",
                  "Bidar",
                  "Chamarajanagar",
                  "Chikballapur",
                  "Chikkamagaluru",
                  "Chitradurga",
                  "Dakshina Kannada",
                  "Davanagere",
                  "Dharwad",
                  "Gadag",
                  "Hassan",
                  "Haveri",
                  "Kalaburagi",
                  "Kodagu",
                  "Kolar",
                  "Koppal",
                  "Mandya",
                  "Mysuru",
                  "Raichur",
                  "Ramanagara",
                  "Shivamogga",
                  "Tumakuru",
                  "Udupi",
                  "Uttara Kannada",
                  "Vijayapura",
                  "Yadgir"
                ]
            },
              {
                state: "Kerala",
                districts: [
                  "Alappuzha",
                  "Ernakulam",
                  "Idukki",
                  "Kannur",
                  "Kasaragod",
                  "Kollam",
                  "Kottayam",
                  "Kozhikode",
                  "Malappuram",
                  "Palakkad",
                  "Pathanamthitta",
                  "Thiruvananthapuram",
                  "Thrissur",
                  "Wayanad"
                ]
              },
              {
                state: "Madhya Pradesh",
                districts: [
                  "Agar Malwa",
                  "Alirajpur",
                  "Anuppur",
                  "Ashoknagar",
                  "Balaghat",
                  "Barwani",
                  "Betul",
                  "Bhind",
                  "Bhopal",
                  "Burhanpur",
                  "Chhatarpur",
                  "Chhindwara",
                  "Damoh",
                  "Datia",
                  "Dewas",
                  "Dhar",
                  "Dindori",
                  "Guna",
                  "Gwalior",
                  "Harda",
                  "Hoshangabad",
                  "Indore",
                  "Jabalpur",
                  "Jhabua",
                  "Katni",
                  "Khandwa",
                  "Khargone",
                  "Mandla",
                  "Mandsaur",
                  "Morena",
                  "Narsinghpur",
                  "Neemuch",
                  "Niwari",
                  "Panna",
                  "Raisen",
                  "Rajgarh",
                  "Ratlam",
                  "Rewa",
                  "Sagar",
                  "Satna",
                  "Sehore",
                  "Seoni",
                  "Shahdol",
                  "Shajapur",
                  "Sheopur",
                  "Shivpuri",
                  "Sidhi",
                  "Singrauli",
                  "Tikamgarh",
                  "Ujjain",
                  "Umaria",
                  "Vidisha"
                ]
              },
              {
                state: "Maharashtra",
                districts: [
                  "Ahmednagar",
                  "Akola",
                  "Amravati",
                  "Aurangabad",
                  "Beed",
                  "Bhandara",
                  "Buldhana",
                  "Chandrapur",
                  "Dhule",
                  "Gadchiroli",
                  "Gondia",
                  "Hingoli",
                  "Jalgaon",
                  "Jalna",
                  "Kolhapur",
                  "Latur",
                  "Mumbai City",
                  "Mumbai Suburban",
                  "Nagpur",
                  "Nanded",
                  "Nandurbar",
                  "Nashik",
                  "Osmanabad",
                  "Palghar",
                  "Parbhani",
                  "Pune",
                  "Raigad",
                  "Ratnagiri",
                  "Sangli",
                  "Satara",
                  "Sindhudurg",
                  "Solapur",
                  "Thane",
                  "Wardha",
                  "Washim",
                  "Yavatmal"
                ]
              },
              {
                state: "Manipur",
                districts: [
                  "Bishnupur",
                  "Chandel",
                  "Churachandpur",
                  "Imphal East",
                  "Imphal West",
                  "Jiribam",
                  "Kakching",
                  "Kamjong",
                  "Kangpokpi",
                  "Noney",
                  "Pherzawl",
                  "Senapati",
                  "Tamenglong",
                  "Tengnoupal",
                  "Thoubal",
                  "Ukhrul"
                ]
              },
              {
                state: "Meghalaya",
                districts: [
                  "East Garo Hills",
                  "East Jaintia Hills",
                  "East Khasi Hills",
                  "North Garo Hills",
                  "Ribhoi",
                  "South Garo Hills",
                  "South West Garo Hills",
                  "South West Khasi Hills",
                  "West Garo Hills",
                  "West Jaintia Hills",
                  "West Khasi Hills"
                ]
              },
              {
                state: "Mizoram",
                districts: [
                  "Aizawl",
                  "Champhai",
                  "Hnahthial",
                  "Khawzawl",
                  "Kolasib",
                  "Lawngtlai",
                  "Lunglei",
                  "Mamit",
                  "Saiha",
                  "Saitual",
                  "Serchhip"
                ]
              },
              {
                state: "Nagaland",
                districts: [
                  "Chümoukedima",
                  "Dimapur",
                  "Kiphire",
                  "Kohima",
                  "Longleng",
                  "Mokokchung",
                  "Mon",
                  "Niuland",
                  "Noklak",
                  "Peren",
                  "Phek",
                  "Shamator",
                  "Tseminyü",
                  "Tuensang",
                  "Wokha",
                  "Zünheboto"
                ]
              },
              {
                state: "Odisha",
                districts: [
                  "Angul",
                  "Balangir",
                  "Balasore",
                  "Bargarh",
                  "Bhadrak",
                  "Boudh",
                  "Cuttack",
                  "Deogarh",
                  "Dhenkanal",
                  "Gajapati",
                  "Ganjam",
                  "Jagatsinghapur",
                  "Jajpur",
                  "Jharsuguda",
                  "Kalahandi",
                  "Kandhamal",
                  "Kendrapara",
                  "Kendujhar",
                  "Khordha",
                  "Koraput",
                  "Malkangiri",
                  "Mayurbhanj",
                  "Nabarangpur",
                  "Nayagarh",
                  "Nuapada",
                  "Puri",
                  "Rayagada",
                  "Sambalpur",
                  "Subarnapur",
                  "Sundargarh"
                ]
              },
              {
                state: "Punjab",
                districts: [
                  "Amritsar",
                  "Barnala",
                  "Bathinda",
                  "Faridkot",
                  "Fatehgarh Sahib",
                  "Fazilka",
                  "Ferozepur",
                  "Gurdaspur",
                  "Hoshiarpur",
                  "Jalandhar",
                  "Kapurthala",
                  "Ludhiana",
                  "Malerkotla",
                  "Mansa",
                  "Moga",
                  "Mohali",
                  "Muktsar",
                  "Nawanshahr",
                  "Pathankot",
                  "Patiala",
                  "Rupnagar",
                  "Sangrur",
                  "Tarn Taran"
                ]
              },
              {
                state: "Rajasthan",
                districts: [
                  "Ajmer",
                  "Alwar",
                  "Banswara",
                  "Baran",
                  "Barmer",
                  "Bharatpur",
                  "Bhilwara",
                  "Bikaner",
                  "Bundi",
                  "Chittorgarh",
                  "Churu",
                  "Dausa",
                  "Dholpur",
                  "Dungarpur",
                  "Hanumangarh",
                  "Jaipur",
                  "Jaisalmer",
                  "Jalore",
                  "Jhalawar",
                  "Jhunjhunu",
                  "Jodhpur",
                  "Karauli",
                  "Kota",
                  "Nagaur",
                  "Pali",
                  "Pratapgarh",
                  "Rajsamand",
                  "Sawai Madhopur",
                  "Sikar",
                  "Sirohi",
                  "Sri Ganganagar",
                  "Tonk",
                  "Udaipur"
                ]
              },
              {
                state: "Sikkim",
                districts: [
                  "East Sikkim",
                  "North Sikkim",
                  "South Sikkim",
                  "West Sikkim",
                  "Pakyong",
                  "Soreng"
                ]
              },
              {
                state: "Tamil Nadu",
                districts: [
                  "Ariyalur",
                  "Chengalpattu",
                  "Chennai",
                  "Coimbatore",
                  "Cuddalore",
                  "Dharmapuri",
                  "Dindigul",
                  "Erode",
                  "Kallakurichi",
                  "Kanchipuram",
                  "Kanyakumari",
                  "Karur",
                  "Krishnagiri",
                  "Madurai",
                  "Mayiladuthurai",
                  "Nagapattinam",
                  "Namakkal",
                  "Nilgiris",
                  "Perambalur",
                  "Pudukkottai",
                  "Ramanathapuram",
                  "Ranipet",
                  "Salem",
                  "Sivaganga",
                  "Tenkasi",
                  "Thanjavur",
                  "Theni",
                  "Thoothukudi",
                  "Tiruchirappalli",
                  "Tirunelveli",
                  "Tirupathur",
                  "Tiruppur",
                  "Tiruvallur",
                  "Tiruvannamalai",
                  "Tiruvarur",
                  "Vellore",
                  "Viluppuram",
                  "Virudhunagar"
                ]
              },
              {
                state: "Telangana",
                districts: [
                  "Adilabad",
                  "Bhadradri Kothagudem",
                  "Hyderabad",
                  "Jagtial",
                  "Jangaon",
                  "Jayashankar Bhupalpally",
                  "Jogulamba Gadwal",
                  "Kamareddy",
                  "Karimnagar",
                  "Khammam",
                  "Komaram Bheem",
                  "Mahabubabad",
                  "Mahabubnagar",
                  "Mancherial",
                  "Medak",
                  "Medchal–Malkajgiri",
                  "Mulugu",
                  "Nagarkurnool",
                  "Nalgonda",
                  "Nirmal",
                  "Nizamabad",
                  "Peddapalli",
                  "Rajanna Sircilla",
                  "Ranga Reddy",
                  "Sangareddy",
                  "Siddipet",
                  "Suryapet",
                  "Vikarabad",
                  "Wanaparthy",
                  "Warangal",
                  "Yadadri Bhuvanagiri"
                ]
              },
              {
                state: "Tripura",
                districts: [
                  "Dhalai",
                  "Gomati",
                  "Khowai",
                  "North Tripura",
                  "Sepahijala",
                  "South Tripura",
                  "Unakoti",
                  "West Tripura"
                ]
              },
              {
                state: "Uttar Pradesh",
                districts: [
                  "Agra",
                  "Aligarh",
                  "Ambedkar Nagar",
                  "Amethi",
                  "Amroha",
                  "Auraiya",
                  "Ayodhya",
                  "Azamgarh",
                  "Badaun",
                  "Baghpat",
                  "Bahraich",
                  "Ballia",
                  "Balrampur",
                  "Banda",
                  "Barabanki",
                  "Bareilly",
                  "Basti",
                  "Bhadohi",
                  "Bijnor",
                  "Bulandshahr",
                  "Chandauli",
                  "Chitrakoot",
                  "Deoria",
                  "Etah",
                  "Etawah",
                  "Farrukhabad",
                  "Fatehpur",
                  "Firozabad",
                  "Gautam Buddha Nagar",
                  "Ghaziabad",
                  "Ghazipur",
                  "Gonda",
                  "Gorakhpur",
                  "Hamirpur",
                  "Hapur",
                  "Hardoi",
                  "Hathras",
                  "Jalaun",
                  "Jaunpur",
                  "Jhansi",
                  "Kannauj",
                  "Kanpur Dehat",
                  "Kanpur Nagar",
                  "Kasganj",
                  "Kaushambi",
                  "Kheri",
                  "Kushinagar",
                  "Lalitpur",
                  "Lucknow",
                  "Maharajganj",
                  "Mahoba",
                  "Mainpuri",
                  "Mathura",
                  "Mau",
                  "Meerut",
                  "Mirzapur",
                  "Moradabad",
                  "Muzaffarnagar",
                  "Pilibhit",
                  "Pratapgarh",
                  "Prayagraj",
                  "Raebareli",
                  "Rampur",
                  "Saharanpur",
                  "Sambhal",
                  "Sant Kabir Nagar",
                  "Shahjahanpur",
                  "Shamli",
                  "Shrawasti",
                  "Siddharthnagar",
                  "Sitapur",
                  "Sonbhadra",
                  "Sultanpur",
                  "Unnao",
                  "Varanasi"
                ]
              },
              {
                state: "Uttarakhand",
                districts: [
                  "Almora",
                  "Bageshwar",
                  "Chamoli",
                  "Champawat",
                  "Dehradun",
                  "Haridwar",
                  "Nainital",
                  "Pauri Garhwal",
                  "Pithoragarh",
                  "Rudraprayag",
                  "Tehri Garhwal",
                  "Udham Singh Nagar",
                  "Uttarkashi"
                ]
              },
              {
                state: "West Bengal",
                districts: [
                  "Alipurduar",
                  "Bankura",
                  "Birbhum",
                  "Cooch Behar",
                  "Dakshin Dinajpur",
                  "Darjeeling",
                  "Hooghly",
                  "Howrah",
                  "Jalpaiguri",
                  "Jhargram",
                  "Kalimpong",
                  "Kolkata",
                  "Malda",
                  "Murshidabad",
                  "Nadia",
                  "North 24 Parganas",
                  "Paschim Bardhaman",
                  "Paschim Medinipur",
                  "Purba Bardhaman",
                  "Purba Medinipur",
                  "Purulia",
                  "South 24 Parganas",
                  "Uttar Dinajpur"
                ]
              },
              {
                state: "Delhi",
                districts: [
                  "Central Delhi",
                  "East Delhi",
                  "New Delhi",
                  "North Delhi",
                  "North East Delhi",
                  "North West Delhi",
                  "Shahdara",
                  "South Delhi",
                  "South East Delhi",
                  "South West Delhi",
                  "West Delhi"
                ]
              },
              {
                state: "Jammu and Kashmir",
                districts: [
                  "Anantnag",
                  "Bandipora",
                  "Baramulla",
                  "Budgam",
                  "Doda",
                  "Ganderbal",
                  "Jammu",
                  "Kathua",
                  "Kishtwar",
                  "Kulgam",
                  "Kupwara",
                  "Poonch",
                  "Pulwama",
                  "Rajouri",
                  "Ramban",
                  "Reasi",
                  "Samba",
                  "Shopian",
                  "Srinagar",
                  "Udhampur"
                ]
              },
              {
                state: "Ladakh",
                districts: [
                  "Kargil",
                  "Leh"
                ]
              },
              {
                state: "Puducherry",
                districts: [
                  "Karaikal",
                  "Mahe",
                  "Puducherry",
                  "Yanam"
                ]
              },
              {
                state: "Andaman and Nicobar Islands",
                districts: [
                  "Nicobar",
                  "North and Middle Andaman",
                  "South Andaman"
                ]
              },
              {
                state: "Chandigarh",
                districts: ["Chandigarh"]
              },
              {
                state: "Dadra and Nagar Haveli and Daman and Diu",
                districts: [
                  "Dadra and Nagar Haveli",
                  "Daman",
                  "Diu"
                ]
              },
              {
                state: "Lakshadweep",
                districts: ["Lakshadweep"]
              }
            ];
                                    
            
       
  
  // This function returns districts for a given state
  export const getDistricts = (state: string): string[] => {
    return stateDistricts[state] || [];
  };
  
  // This is a simplified city list function
  // In a real app, this would be connected to a comprehensive API
  export const getCities = (district: string): string[] => {
    // For simplicity, we're returning a fixed set of sample cities
    // In a real app, this would return cities specific to the district
    const sampleCities = [
      `${district} North`,
      `${district} South`,
      `${district} East`,
      `${district} West`,
      `${district} Central`,
      "New Area",
      "Old Area",
    ];
    
    return sampleCities;
  };
  